### ISSUE TITLE
*Screenshot* of LaunchRequestHandler gives incorrect birthday for Alexa

### ISSUE THREAD

**Issue by dianeo** [alexa/skill-sample-python-first-skill#18]
The code in the console is correct. But the screenshot shows:

reprompt_text = "I was born Nov. 6th, 2015. When are you born?"

Alexa was born in 2014, not 2015.

**Comment by dianeo** [comment]
Also, "When are you born?" in the sample code is incorrect. It should be "When were you born?". The screenshot has the correct text.

**Comment by JoeMoCode** [comment]
Thanks for raising this! I fixed the text
