### ISSUE TITLE
Possible console bug?

### ISSUE THREAD

**Issue by dianeo** [alexa/skill-sample-python-first-skill#19]
In Module 2, step 1, I add the reprompt text, save, and deploy, but Alexa skips over it. She asks me for my birthday and then stops! (If I reply, she says, "Hello World!", which is of course correct.

Here's what I've got:

class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool

        return ask_utils.is_request_type("LaunchRequest")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        speak_output = "Hello! This is Cake walk. What is your birthday?"
        reprompt_text = "I was born Nov. 6th, 2014. When were you born?"

        return (
            handler_input.response_builder
                .speak(speak_output)
                .ask(reprompt_text)
                .response
        )

**Comment by dianeo** [comment]
Aha, it's not just me! See https://forums.developer.amazon.com/questions/216618/cake-walk-askreprompt-text-python-and-repromptrepr.html

**Comment by JoeMoCode** [comment]
Hi Dianeo, You will not hear the reprompt text to speech when using the console. You will need to use an Alexa-enabled device to view the reprompt. 

I hope this clarifies. Please reopen if you believe there is still a problem with this code.
