### ISSUE TITLE
Module4 error on pasting the lambda_function.py

### ISSUE THREAD

**Issue by AneshkaGoyal** [alexa/skill-sample-python-first-skill#20]
The code of lambda_function.py is pasted after copying from github and the requirements.txt is also validated to be the same as required but on testing the response received is "There was a problem with the requested skill's response"

**Comment by kishhh** [comment]
seeing the same issue, hitting the try/catch in HasBirthdayLaunchRequestHandler

**Comment by dustindaon** [comment]
This is possibly from these lines inside of def handle() in HasBirthdayLaunchRequestHandler:
        year = attr['year']
        month = attr['month'] # month is a string, and we need to convert it to a month index later
        day = attr['day']

They are all using a single quotation mark when they should be using two, ie: 
        year = attr["year"]
        month = attr["month"] # month is a string, and we need to convert it to a month index later
        day = attr["day"]

**Comment by ashley-iyqw** [comment]
The line `month_as_index = list(calendar.month_abbr).index(month[:3])` might be where the error is. Month is stored as lower case chars like 'march'. In calendar.month_abbr, things are stored like 'Jan', 'Mar', etc. 

`month_as_index = list(calendar.month_abbr).index(month[:3].capitalize())` should fix it.

**Comment by ajot** [comment]
Fixed with https://github.com/alexa/skill-sample-python-first-skill/commit/d896e975916e46dcf58cd59ed8db15223afb970f#diff-2500b0339e08aae0674ef3f9a87ade5b
