### ISSUE TITLE
add step 2g: 'Select Hello World Skill'

### ISSUE THREAD

**Issue by sahmel** [alexa/skill-sample-python-first-skill#35]
After step 2f, an additional option is presented to the user to 'Choose a template to add to your skill' that is not included in the tutorial. It would seem logical to choose the 'Cake Walk (tutorial)' but this code does not sync with the tutorial steps. The 'Hello World Skill' option must be chosen. 
<img width="1358" alt="Screen_Shot_Hello_World" src="https://user-images.githubusercontent.com/28521731/80868039-f2b8bc00-8c65-11ea-9f4e-1102b79d5a7e.png">

**Comment by thisisMikeSimon** [comment]
@sahmel Thank you for this :)

**Comment by ajot** [comment]
@sahmel thanks for pointing this out. References https://github.com/alexa/skill-sample-python-first-skill/pull/38

**Comment by Amit-GH** [comment]
The Hello world skill has been renamed to 'Start from Scratch'.

**Comment by aszk** [comment]
I have added a step to select Start from Scratch. Thank you so much for the feedback.
