### ISSUE TITLE
Module 1: Can't Make Alexa say what I input in Speak_output

### ISSUE THREAD

**Issue by thisisMikeSimon** [alexa/skill-sample-python-first-skill#36]
Hi, at first I used the Cake Walk Tutorial template, then I changed it to Hello World Template since the Python Coding shows correct on there;I saved and deployed my Cake Walk coding and tried to program it to say " Hello! Welcome to cake walk. That was a piece of cake! Bye!" on the Speak_output function, but instead when i test the coding Alexa, said something along the lines of "Hello, I was created on.....What is your birthday?" I replied with my birth date to it, then I said "Open Cake Walk", and it replied to me incorrectly, "Welcome back. It looks like there are 300 days until your -109973th birthday." So i went and altered the speak_output  function to say "Hello Sunshine" and when tested the code after saving and deploying Alexa said the same thing "Welcome back. It looks like there are 300 days until your -109973th birthday." Keeping everything the same, I manually changed the Invocation name to "Cake walk", it was prepolated with "change name", then tested it again by saving and deploying and same problem. Lastly, i went back and changed the speak_output to what I originally had "Hello! Welcome to cake walk. That was a piece of cake! Bye!";then i saved, deployed, and tested and Same Issue. Looks like a console problem, but as I may be wrong it could just be my coding, help please? 

Here's my Code in Python:
# -*- coding: utf-8 -*-

# This sample demonstrates handling intents from an Alexa skill using the Alexa Skills Kit SDK for Python.
# Please visit https://alexa.design/cookbook for additional examples on implementing slots, dialog management,
# session persistence, api calls, and more.
# This sample is built using the handler classes approach in skill builder.
import logging
import ask_sdk_core.utils as ask_utils

from ask_sdk_core.skill_builder import SkillBuilder
from ask_sdk_core.dispatch_components import AbstractRequestHandler
from ask_sdk_core.dispatch_components import AbstractExceptionHandler
from ask_sdk_core.handler_input import HandlerInput

from ask_sdk_model import Response

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

class LaunchRequestHandler(AbstractRequestHandler):
    """Handler for Skill Launch."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool

        return ask_utils.is_request_type("LaunchRequest")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        speak_output = "Hello! Welcome to cake walk. That was a piece of cake! Bye!"

        return (
            handler_input.response_builder
                .speak(speak_output)
                #.ask(speak_output)
                .response
        )

class HelloWorldIntentHandler(AbstractRequestHandler):
    """Handler for Hello World Intent."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool
        return ask_utils.is_intent_name("HelloWorldIntent")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        speak_output = "Hello World!"

        return (
            handler_input.response_builder
                .speak(speak_output)
                # .ask("add a reprompt if you want to keep the session open for the user to respond")
                .response
        )

class HelpIntentHandler(AbstractRequestHandler):
    """Handler for Help Intent."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool
        return ask_utils.is_intent_name("AMAZON.HelpIntent")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        speak_output = "You can say hello to me! How can I help?"

        return (
            handler_input.response_builder
                .speak(speak_output)
                .ask(speak_output)
                .response
        )

class CancelOrStopIntentHandler(AbstractRequestHandler):
    """Single handler for Cancel and Stop Intent."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool
        return (ask_utils.is_intent_name("AMAZON.CancelIntent")(handler_input) or
                ask_utils.is_intent_name("AMAZON.StopIntent")(handler_input))

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        speak_output = "Goodbye!"

        return (
            handler_input.response_builder
                .speak(speak_output)
                .response
        )

class SessionEndedRequestHandler(AbstractRequestHandler):
    """Handler for Session End."""
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool
        return ask_utils.is_request_type("SessionEndedRequest")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response

        # Any cleanup logic goes here.

        return handler_input.response_builder.response

class IntentReflectorHandler(AbstractRequestHandler):
    """The intent reflector is used for interaction model testing and debugging.
    It will simply repeat the intent the user said. You can create custom handlers
    for your intents by defining them above, then also adding them to the request
    handler chain below.
    """
    def can_handle(self, handler_input):
        # type: (HandlerInput) -> bool
        return ask_utils.is_request_type("IntentRequest")(handler_input)

    def handle(self, handler_input):
        # type: (HandlerInput) -> Response
        intent_name = ask_utils.get_intent_name(handler_input)
        speak_output = "You just triggered " + intent_name + "."

        return (
            handler_input.response_builder
                .speak(speak_output)
                # .ask("add a reprompt if you want to keep the session open for the user to respond")
                .response
        )

class CatchAllExceptionHandler(AbstractExceptionHandler):
    """Generic error handling to capture any syntax or routing errors. If you receive an error
    stating the request handler chain is not found, you have not implemented a handler for
    the intent being invoked or included it in the skill builder below.
    """
    def can_handle(self, handler_input, exception):
        # type: (HandlerInput, Exception) -> bool
        return True

    def handle(self, handler_input, exception):
        # type: (HandlerInput, Exception) -> Response
        logger.error(exception, exc_info=True)

        speak_output = "Sorry, I had trouble doing what you asked. Please try again."

        return (
            handler_input.response_builder
                .speak(speak_output)
                .ask(speak_output)
                .response
        )

# The SkillBuilder object acts as the entry point for your skill, routing all request and response
# payloads to the handlers above. Make sure any new handlers or interceptors you've
# defined are included below. The order matters - they're processed top to bottom.

sb = SkillBuilder()

sb.add_request_handler(LaunchRequestHandler())
sb.add_request_handler(HelloWorldIntentHandler())
sb.add_request_handler(HelpIntentHandler())
sb.add_request_handler(CancelOrStopIntentHandler())
sb.add_request_handler(SessionEndedRequestHandler())
sb.add_request_handler(IntentReflectorHandler()) # make sure IntentReflectorHandler is last so it doesn't override your custom intent handlers

sb.add_exception_handler(CatchAllExceptionHandler())

lambda_handler = sb.lambda_handler()

**Comment by LetMyPeopleCode** [comment]
This is usually not a problem with your code, but your invocation name. You're actually opening someone else's cake walk.

Go, change the invocation name to something like "the big cake," then save and rebuild your interaction model, then use that new invocation name. That should prevent any accidental invocation of another person's skill.

**Comment by thisisMikeSimon** [comment]
Hi @YiddishNinja Thank you for your help. I did as you said and this is what happened.  
<img width="433" alt="Screen Shot 2020-05-06 at 8 51 18 AM" src="https://user-images.githubusercontent.com/64875768/81198943-ea6ac480-8f76-11ea-8c90-8d1e58737794.png">

Shouldn't it have said " Hello! Welcome to cake walk. That was a piece of cake! Bye!"  at the beginning. It worked but after i repeated myself. Would love your thoughts and thank you for your time.

**Comment by thisisMikeSimon** [comment]
Interestingly enough I clicked the tabs "code" then "Test" again, and it worked just fine: 
<img width="425" alt="Screen Shot 2020-05-06 at 8 56 40 AM" src="https://user-images.githubusercontent.com/64875768/81199482-901e3380-8f77-11ea-9a6c-6184914ed9f4.png">

Now moving on to the next modules thank you my friend.
