### ISSUE TITLE
No mention of invocation name

### ISSUE THREAD

**Issue by heywoodg** [alexa/skill-sample-python-first-skill#39]
Thanks for doing this tutorial. 

The invocation name defaults to "change me." You need to change it to "cake walk", and then do a "build model" before it will work. 

I think you may need to wait a few minutes for the build to complete too?

**Comment by tonytec09** [comment]
I was wondering the same thing.
When I go test, it's like Alexa already knows the full code and I am only in the first module!

**Comment by ajot** [comment]
Thanks for pointing this out @heywoodg and @tonytec09. You think this change would help? https://github.com/alexa/skill-sample-python-first-skill/pull/42

**Comment by jbnunn** [comment]
Resolving via https://github.com/alexa/skill-sample-python-first-skill/pull/42
