### ISSUE TITLE
Module 3 giving error - "Sorry, I couldn't understand what you said. Please try again." 

### ISSUE THREAD

**Issue by KunjalRupala** [alexa/skill-sample-python-first-skill#4]
Whenever I try to test my code and ask alexa to "open cake walk", it responds me with this error - "Sorry, I couldn't understand what you said. Please try again." 

I am using the same code thats given in lambda_function.py of module 3.

My requirement file's content are same as the requirements file present in module 3:
```
ask-sdk-core
ask-sdk-s3-persistence-adapter
```
Thanks in advance.

**Comment by geriskenderi** [comment]
Check the answers [in this other issue](https://github.com/alexa/skill-sample-python-first-skill/issues/2#issuecomment-544502759), I believe you can find an answer there.

**Comment by THEMADDIX** [comment]
there are some problem

**Comment by JoeMoCode** [comment]
Resolving as this has been open a while and there were changes to the code since. Please, open a new issue if you think there is a problem with this repo.
