### ISSUE TITLE
No such function attributes_manager.save_persistent_attributes(), seems broken

### ISSUE THREAD

**Issue by jayshar2222** [alexa/skill-sample-python-first-skill#44]
Seems like there is no function defined for save_persistent_attributes() for attributes_manager object, so my code it is not showing up as a purple colored function as it should if it was a defined function. I am getting an invalid return prompt when i provide the year of my birthday, Alexa responds "HelloWorldIntent was invoked" or something similar. It was working fine and Alexa responded with "Thanks! I'll remember your birthday is on month, data, year" before putting in the S3 persistence code as per the tutorial.

**Comment by jayshar2222** [comment]
Slight correction - Alexa responds "You just triggered HelloWorldIntent" now.

**Comment by jayshar2222** [comment]
![image](https://user-images.githubusercontent.com/61483319/98051761-5ffe0300-1de9-11eb-9408-383733d5e702.png)

**Comment by aszk** [comment]
Can you check your interaction model and code? I am not sure which steps you are on but the final interaction model and code [here](https://github.com/alexa-samples/skill-sample-python-first-skill/tree/master/final). The intent that responded was IntentReflectorHandler that tells you which intent was triggered if suitable intent doesn't exist in your code.

**Comment by aszk** [comment]
Closing.
