### ISSUE TITLE
Not able to delete the s3 instance memory

### ISSUE THREAD

**Issue by VenkateshDas** [alexa/skill-sample-python-first-skill#47]
After invoking the cake time skill and setting the birthday, I am not able to delete the memory from the s3 instance as illustrated in the tutorial. I am getting an error message as : "You don’t have permission to get the Bucket Versioning setting".

Is there any way to delete the instance memory? 

I have also uploaded the screenshot for this issue. 
<img width="854" alt="Screenshot 2020-12-15 at 10 03 50 PM" src="https://user-images.githubusercontent.com/17122430/102272780-9454fb00-3f21-11eb-9794-12713a3deee9.png">

**Comment by Amit-GH** [comment]
Not sure if this will help but you don't have to delete the bucket. I see that even I do not have permissions to delete the bucket. You just need to delete the file that has been created in the bucket. Go to 'Objects' tab and find the file having name `amzn1.ask.account...`. Deleting this file will delete 'memory' of the Alexa skill.
