### ISSUE TITLE
Skill is fully functional after completing just the first module

### ISSUE THREAD

**Issue by namannik** [alexa/skill-sample-python-first-skill#48]
After completing the first module, when testing the skill, I entered "Open Cake Time", as instructed.  Instead of receiving the response created in this module ("Hello! Welcome to Cake Time. That was a piece of cake! Bye!"), Cake Time asks for my birthday.  It appears that this demo project has been promoted to live production.

**Comment by LetMyPeopleCode** [comment]
Yes, a few Cake Times got published. The main trick is that when you start the skill, the actual invocation name is "change me," and if you haven't changed that and rebuilt your model, "open cake time" cannot invoke your skill and it will look for an available one with that launch phrase.

The usual suggestion we give in workshops if someone misses this step is to change the invocation name to something like "my [random word] cake time" and then rebuild your model. Next time you try to launch it, use your new invocation name. You can just change the invocation name to Cake Time, but now that you've launched the other one, the algorithm might assume that's the one you mean. Best to try to come up with an original invocation.

Closing this, but if you still run into trouble, please reply.

**Comment by namannik** [comment]
Thanks for the information.  I did change my invocation name to "Cake Time Demo", and this worked fine.  I recommend updating the documentation to describe how to change the invocation name.  (This is not included in the step-by-step walkthrough.)
