### ISSUE TITLE
Module 2 Python Issue

### ISSUE THREAD

**Issue by Groovemood** [alexa/skill-sample-python-first-skill#49]
Hello, 

I have followed all the steps in module 2 and even copied and pasted the sample but when I test and say "open cake time". It responds, "Ok, Here's Cake Walk" "Hello! Welcome to cake walk. That was a piece of cake! Bye!".

I am not sure what I am doing wrong... Please help.

Thank you,

**Comment by grantwforsythe** [comment]
Hi,

Not sure if you have found a solution to your problem but I assume the issue lies within the `handler_input.response_builder` method. (I don't have a lot to go off of without seeing your source code).

**Comment by LetMyPeopleCode** [comment]
We have this issue with the JavaScript sample often. The initial "Hello World" starts with a skill name of "change me." If you don't change it before the first time you try to invoke the skill, you just invoke someone else's older skill and this used to be called Cake Walk. 

Usually, at that point, you have their skill enabled for your account.

You need to go to the **Build** tab, change the **Invocation Name** to something like "cake time me", save and build your model, then use "open cake time me" as your invocation from then on.
