### ISSUE TITLE
Local debugging in VS Code with module 4 needs S3 credentials

### ISSUE THREAD

**Issue by Amit-GH** [alexa/skill-sample-python-first-skill#52]
I am trying to setup local debugger with this example cake skill. I am able to connect the debugger but see issues in making connections with S3. This problem is not seen if I do not connect the debugger and simply test the skill using Alexa Simulator in the UI. 

I had to make some changes to make the code work locally too with vs code. First, I replaced `os.environ` with `os.getenv`. The line to get s3_adapter is now
```
s3_adapter = S3Adapter(bucket_name=os.getenv("S3_PERSISTENCE_BUCKET"))
```
Second, the variable S3_PERSISTENCE_BUCKET is not present locally so we need to manually add it and set it to the correct bucket name. In my case, I had to make updates in the `launch.json` file to add a `env`. The edited section looks like the following:
```
...
"env": {
    // This is the default bucket created for my account. This is needed for local debugging.
    // When run in AWS, this environment variable is already stored.
    "S3_PERSISTENCE_BUCKET" : "0cbd013c-d5f5-4359-aa8d-3d3a9a1cca16-us-east-1"
},
"console": "internalConsole",
"cwd": "${workspaceFolder}/lambda"
...
``` 

With these changes done, now the error that remains is credential. In `HasBirthdayLaunchRequestHandler.can_handle()` method, line `attr = handler_input.attributes_manager.persistent_attributes` throws error. Pasting the main content below. It makes sense as I have not done anything to add credentials. Setting credentials doesn't seem necessary when the skill runs on AWS without debugging. I needed some help in setting up the credentials so that his module also works with local debugging. Thanks.
```
    raise NoCredentialsError
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

**Comment by Amit-GH** [comment]
I was able to resolve this (in a way). The problem which I found is that the default S3 bucket which is created with the lambda application (developer console > Code > S3 Storage) has limited permissions. If you check permissions for the bucket, you'll notice many Notes with a red cross. Most permissions are not even visible to us. So you need to create a separate bucket and use that for storing the birthday data.

In the above exception, I was initially getting `NoCredentialsError`. That went away after I correctly configured AWS permissions. Then I was getting `permission denied error` which went away after creating another S3 bucket. Mentioning the rough steps which I followed.

1. Install node and npm [link](https://developer.amazon.com/en-US/docs/alexa/smapi/quick-start-alexa-skills-kit-command-line-interface.html).
2. Download the AWS CLI locally [link](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-mac.html#cliv2-mac-install-confirm).
3. Run `aws configure` and set the correct credentials [link](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html).
4. Create a new bucket using your AWS account and use that in the "S3_PERSISTENCE_BUCKET".
5. Run debugger as usual.

**Comment by aszk** [comment]
Closing. The issue has been resolved by the reporter.
