### ISSUE TITLE
Remember birthday with problem

### ISSUE THREAD

**Issue by krsmga** [alexa/skill-sample-python-first-skill#53]
I copied the code in its entirety, with me it works correctly to capture the birthday. But when I run it the second time the simulator just responds. I didn't make any changes to the code.

Sorry, I had trouble doing what you asked. Please try again.

**Comment by sateesh12** [comment]
I am getting an error at run-time. How did you solve please @krsmga

**Comment by sateesh12** [comment]
[Solved] issue in my code syntax, not  caught by python interpreter !

**Comment by aszk** [comment]
@krsmga Sorry for late response. I assume that your skill session hasn't ended. Could you try to say close and make sure if the session is done, then invoke the skill again?

**Comment by aszk** [comment]
Closing.
